### ISSUE TITLE
TS环境下需要注意的地方

### ISSUE THREAD

**Issue by dvlin-dev** [neohan666/react-antd-mobx-admin#2]
非常感谢您的模板，另外我在TypeScript环境下做了一些改造，希望能帮助使用这个模板的开发者。

router->index.ts
```javascript
// 在TS环境下这样写是不被允许的
element: <PageLayout /> ,
icon: <HomeOutlined />,

// 应该这样
element: PageLayout ,
icon: HomeOutlined ,
```
当然这样写必须相应地方也应该做出改变
layout -> index.tsx
```js
-  export default PageLayout ;
+  export default <PageLayout />;
```

layout -> sideBar.tsx
```js
-            <SubMenu key={currentPath} title={v.meta.title} icon={v.meta.icon}>
+            <SubMenu key={currentPath} title={v.meta.title} icon={v.meta.icon && <v.meta.icon />}>                   

```

如果不进行修改 会有导致模板无法使用

最后再次感谢您提供的方案。

**Comment by neohan666** [comment]
感谢热心分享，不过我想了解一下为什么那样写不可以？报什么错？有没有尝试在 router->index.ts 里导入react模块？

**Comment by dvlin-dev** [comment]
我用的React 版本为17.0.2，并进行了相关配置，所以应该和这没有关系。
报错如下
![image](https://user-images.githubusercontent.com/59828992/158547780-cd2baa65-8719-4172-84f2-a19d0e322aa6.png)

**Comment by dvlin-dev** [comment]
在sideBar.tsx中
若这样写
```js
<Menu.Item key={currentPath}  icon={<v.meta.icon />}>
```
会报下面的错误
![image](https://user-images.githubusercontent.com/59828992/158548207-4ffeb18e-258f-4cbd-8140-906bfffce1c5.png)

**Comment by neohan666** [comment]
> 我用的React 版本为17.0.2，并进行了相关配置，所以应该和这没有关系。 报错如下 ![image](https://user-images.githubusercontent.com/59828992/158547780-cd2baa65-8719-4172-84f2-a19d0e322aa6.png)

看报错信息有可能是这个原因，js里使用jsx语法不用引入react上下文，ts里就需要引入，你可以试试 router->index.ts 里 import react from 'react'

**Comment by dvlin-dev** [comment]
> > 我用的React 版本为17.0.2，并进行了相关配置，所以应该和这没有关系。 报错如下 ![image](https://user-images.githubusercontent.com/59828992/158547780-cd2baa65-8719-4172-84f2-a19d0e322aa6.png)
> 
> 看报错信息有可能是这个原因，js里使用jsx语法不用引入react上下文，ts里就需要引入，你可以试试 router->index.ts 里 import react from 'react'

他看起来行不通
![image](https://user-images.githubusercontent.com/59828992/158549841-f3a245e9-5aae-4345-9de3-7fede2c48ee9.png)

**Comment by neohan666** [comment]
奥不对，记错了，应该是文件后缀名改一下，router->index.ts 改成 index.tsx

**Comment by dvlin-dev** [comment]
> 奥不对，记错了，应该是文件后缀名改一下，router->index.ts 改成 index.tsx

amazing , 正常运行了
